name: Verify PR name, Maven build and test (unit & integration) and trivy fs scan

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches: [main]

permissions:
  pull-requests: write
  contents: write
  issues: write
  repository-projects: read

jobs:

  call-workflow-maven-build:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-build.yml@main
    with:
      java-version: 21
      maven-lifecycle: verify
    secrets: inherit
