name: CI Workflow

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [ ] # Empty list ensures PRs are not triggered. Trigger nytt bygg............

jobs:
  release-to-github-packages:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-install-deploy-lib.yml@efm-tilpasninger-2
    with:
      java-version: 11
    secrets: inherit

  call-workflow-image-build-publish:
    needs: [ release-to-github-packages ]
    uses: felleslosninger/github-workflows/.github/workflows/ci-spring-boot-build-publish-image.yml@main
    with:
      image-name: efm-kosmos
      java-version: 11
      slack-channel-id: C05NLQCFR41
      update-versions: "false"
    secrets: inherit