name: CI Workflow

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [ ] # Empty list ensures PRs are not triggered.

jobs:
  #deploys libs to github packages
  build-and-deploy-libs:
    #if: github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '[run-ci]')
    if: github.ref == 'refs/heads/disabled4now' || contains(github.event.head_commit.message, '[run-ci]')
    #uses: felleslosninger/github-workflows/.github/workflows/ci-maven-install-deploy-lib.yml@MOVE-4223
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-install-deploy-lib.yml@main
    with:
      java-version: 21
    secrets: inherit
