name: Call Release

on:
  release:
    types: [created]

jobs:
  call-workflow-ci-build-deploy-lib:
    uses: felleslosninger/github-workflows/.github/workflows/ci-build-publish-lib.yml@main
    permissions:
      contents: write
      packages: write
      actions: read
    with:
      package-version: ${{ github.event.release.tag_name }}
      deployment-repository: ${{ github.repository }}
      java-version: 21
      sbom-path: ./
    secrets: inherit
