name: CI Workflow

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [ ] # Empty list ensures PRs are not triggered. Trigger nytt bygg..

jobs:
  build-and-deploy-libs:
    uses: felleslosninger/github-workflows/.github/workflows/ci-efm-integrasjonspunkt-publish-ossrh.yml@main
    with:
      java-version: 11
    secrets: inherit
    